import assert from 'node:assert/strict';
import { Character } from '../app/js/model.js';
import { blankDocument } from '../app/js/convert.js';
import { sessionRolls, sessionRollSpec } from '../app/js/model/session-rolls.js';
import { weaponRollSpec } from '../app/js/roll20.js';
import { renderSessionBoard } from '../app/js/ui/panels/session.js';
const doc = blankDocument({ name: 'Action rolls', level: 10 });
doc.equipment.weapons = [{ name: 'Sword', attackType: 'Melee', dice: '2d6', damageAbility: 'Str', abilityMult: 1, range: 'Melee' }];
const m = new Character(doc);
const linked = { title: 'Strike', type: 'standard', source: 'attack:Sword' };
let result = sessionRolls(m, linked);
assert.deepEqual(result.spec.rolls, weaponRollSpec(m.data, 0, m.conditionState, null, true).rolls);
assert.equal(result.range, 'Melee');
assert.ok(result.attack.startsWith('+'));
m.set('conditions', { sickened: true });
result = sessionRolls(m, linked);
assert.deepEqual(result.spec.rolls, weaponRollSpec(m.data, 0, m.conditionState, null, true).rolls, 'condition adjustments match existing rolls');
const custom = { title: 'Blast', type: 'standard', attackFormula: 'attack.ranged', damageFormula: '{floor(level / 2)}d6 + str.mod', range: '30 ft.', targets: 'One creature', save: 'Reflex {caster.dc}', note: 'A note' };
result = sessionRolls(m, custom);
assert.equal(result.errors.length, 0);
assert.ok(result.damage.startsWith('5d6'));
assert.equal(result.spec.rolls[0].formula, `1d20${m.conditionState.adjusted.ranged >= 0 ? '+' : ''}${m.conditionState.adjusted.ranged}`.replace(/\+0$/, ''));
assert.equal(sessionRolls(m, { damageFormula: '2d6 + floor(level / 2)' }).damage, '2d6+5');
assert.equal(sessionRolls(m, { damageFormula: '2d6 + 1d8 - 3' }).damage, '1d8+2d6-3');
assert.equal(sessionRolls(m, { damageFormula: '2d6--1d6' }).damage, '3d6');
for (const damageFormula of ['2 * 1d6', '1d0', '2d6 + unknown', '1d6 | malicious', '1d6 + 1/0']) {
  assert.ok(sessionRolls(m, { damageFormula }).errors.length, damageFormula);
}
assert.ok(sessionRolls(m, { attackFormula: 'unknown' }).errors.length);
m.set('session.cards', [custom]);
assert.equal(sessionRollSpec(m, '0:damage').rolls.length, 1);
assert.equal(sessionRollSpec(m, '0:attack').rolls[0].label, 'Attack');
const reopened = new Character(JSON.parse(JSON.stringify(m.toJSON())));
assert.deepEqual(sessionRolls(reopened, reopened.data.session.cards[0]), sessionRolls(m, custom));
const override = sessionRolls(m, { ...linked, attackFormula: '12', damageFormula: '3d8+2' });
assert.deepEqual(override.spec.rolls, [{label:'Attack',formula:'1d20+12'},{label:'Damage',formula:'3d8+2'}]);
const html = renderSessionBoard(m);
assert.ok(html.includes('session-roll-values'));
assert.ok(html.includes('5d6'));
m.set('session.cards.0.targets', '<img src=x onerror=alert(1)>');
assert.ok(!renderSessionBoard(m).includes('<img src=x'));
console.log('Session rolls: linked values, conditions, custom formulas, validation, separate rolls and persistence passed');
