import assert from 'node:assert/strict';
import { Character, setManeuverCatalogue, setVeilCatalogue } from '../app/js/model.js';
import { blankDocument } from '../app/js/convert.js';
import { actionBudget, sessionState, useSessionAction, advanceTurn, sessionShortcuts } from '../app/js/model/session.js';
import { renderSessionBoard } from '../app/js/ui/panels/session.js';
const fresh = () => new Character(blankDocument({ name: 'Session test', level: 5 }));
const use = (m, type, extra = {}) => useSessionAction(m, { type, ...extra });
let m = fresh();
assert.equal(use(m, 'move'), '');
assert.equal(use(m, 'move'), '');
assert.equal(actionBudget(m).standard.remaining, 0);
assert.match(use(m, 'standard'), /No standard/);
m.undo();
assert.equal(actionBudget(m).standard.remaining, 1);
assert.match(use(m, 'full'), /No movement/);
assert.equal(actionBudget(m).standard.remaining, 1, 'failed full-round is atomic');
advanceTurn(m, true);
assert.equal(use(m, 'full'), '');
assert.equal(actionBudget(m).move.remaining, 0);
advanceTurn(m, true);
assert.equal(use(m, 'swift'), '');
assert.equal(actionBudget(m).immediate.remaining, 0);
assert.match(use(m, 'immediate'), /No immediate/);
advanceTurn(m, false);
assert.equal(use(m, 'immediate'), '', 'off-turn immediate can borrow next swift');
assert.equal(sessionState(m).pendingSwift, 1);
m = new Character(JSON.parse(JSON.stringify(m.toJSON())));
assert.equal(sessionState(m).pendingSwift, 1, 'borrowed swift survives reopening');
assert.match(use(m, 'immediate'), /No immediate/);
assert.match(use(m, 'standard'), /Start your turn/);
advanceTurn(m, true);
assert.equal(actionBudget(m).swift.remaining, 0);
assert.equal(actionBudget(m).immediate.remaining, 0);
advanceTurn(m, false);
assert.equal(actionBudget(m).immediate.remaining, 1, 'immediate unlocks after owed turn ends');
advanceTurn(m, true);
assert.equal(actionBudget(m).swift.remaining, 1);
m.set('session.maxima.aoo', '1 + max(0, dex.mod)');
assert.equal(actionBudget(m).aoo.max, 1);
m.set('extras.approvalNotes', '{actions.aoo += 3}');
assert.equal(actionBudget(m).aoo.max, 4, 'bonuses target action maxima');
m.set('session.maxima.standard', 'unknown_variable');
assert.ok(actionBudget(m).standard.error);
assert.ok(use(m, 'standard'));
m = fresh();
m.trackers.push({ id: 'test', name: 'Power', min: 0, current: 1, max: 3, maxFormula: '3', minFormula: '0', source: 'player' });
assert.match(use(m, 'standard', { resource: 'test', cost: '3' }), /Not enough/);
assert.equal(actionBudget(m).standard.remaining, 1);
assert.equal(m.trackers.find(t => t.id === 'test').current, 1);
assert.equal(use(m, 'standard', { resource: 'test', cost: '2' }), '');
assert.equal(m.trackers.find(t => t.id === 'test').current, 3);
m.undo();
assert.equal(m.trackers.find(t => t.id === 'test').current, 1);
assert.equal(actionBudget(m).standard.remaining, 1);
m.set('session.cards', [{ type: 'standard', title: '<img src=x onerror=alert(1)>', note: '<script>bad</script>' }]);
m.set('session.folded.move', true);
const reopened = new Character(JSON.parse(JSON.stringify(m.toJSON())));
assert.deepEqual(sessionState(reopened), sessionState(m));
assert.equal(reopened.trackers.find(t => t.id === 'test').current, 1, 'resource restored with the session');
const html = renderSessionBoard(m);
assert.ok(html.includes('&lt;img'));
assert.ok(!html.includes('<script>bad'));
m.set('equipment.weapons', [{ name: 'Sword' }, { name: 'Bow' }]);
assert.equal(sessionShortcuts(m).find(s => s.key === 'attack:Sword').index, 0);
m.set('equipment.weapons', [{ name: 'Bow' }, { name: 'Sword' }]);
assert.equal(sessionShortcuts(m).find(s => s.key === 'attack:Sword').index, 1);
assert.match(use(m, 'standard', { source: 'attack:Missing' }), /missing/);
m.set('equipment.weapons', [{ name: 'Blade', attackType: 'Melee' }, { name: 'Blade', attackType: 'Alt Melee' }, { name: 'Blade', attackType: 'Alt Melee' }, { name: 'Bow' }]);
assert.deepEqual(sessionShortcuts(m).filter(s => s.kind === 'attack').map(s => [s.key, s.index]),
  [['attack:Blade (Melee)', 0], ['attack:Blade (Alt Melee 1)', 1], ['attack:Blade (Alt Melee 2)', 2], ['attack:Bow', 3]],
  'same-named attack rows stay linkable, told apart by type and order');
assert.equal(use(m, 'standard', { source: 'attack:Blade (Alt Melee 2)' }), '', 'a disambiguated attack resolves');
m.set('featGroups', [{ name: 'Level Up', entries: [{ name: 'Power Attack', detail: '', note: '' }] }]);
const abilityTitles = sessionShortcuts(m).filter(s => s.kind === 'ability').map(s => s.title);
assert.ok(abilityTitles.includes('Power Attack'), 'feats are linkable');
assert.ok(!abilityTitles.includes('Level Up'), 'feat group names are slots, not abilities');
// Maneuvers and veils take their card from the catalogues, and a maneuver is offered under its own action.
setManeuverCatalogue({ disciplines: [{ name: 'Black Seraph', entries: [
  { level: 1, kind: 'maneuver', name: 'Gutstrike', type: 'Strike', action: 'Standard', range: 'Melee attack', target: 'One creature', duration: '1 round', save: 'Fortitude negates', dc: '{= 11 + wis.mod}', text: 'Make an attack.' },
  { level: 1, kind: 'stance', name: 'Savage Stance', type: 'Stance', action: 'Swift', range: 'Personal', target: 'You', duration: 'Stance', text: 'A stance.' },
  { level: 2, kind: 'maneuver', name: 'Odd Trick', type: 'Boost', action: 'See text', text: 'Read it.' }] }] });
setVeilCatalogue({ veils: [{ name: "Marilith's Aspect", slot: 'Shoulders', descriptor: 'Fleshwarp', text: 'Grow two arms.' }] });
m.set('maneuvers.disciplines', [{ name: 'Black Seraph', known: ['Gutstrike', 'Savage Stance', 'Odd Trick'] }]);
m.set('akashic.slots', [{ slot: 'Shoulders', veils: [{ name: "Marilith's Aspect", essence: 2 }] }]);
const byKey = key => sessionShortcuts(m).find(s => s.key === key);
assert.deepEqual([byKey('maneuver:Gutstrike').actionType, byKey('maneuver:Savage Stance').actionType, byKey('maneuver:Odd Trick').actionType], ['standard', 'swift', ''], 'the catalogue action decides the group');
assert.equal(byKey('maneuver:Gutstrike').note, 'Make an attack.', 'the card carries the rules text alone; the facts have their own row');
assert.equal(byKey('maneuver:Gutstrike').detail, 'Strike · Standard action · Black Seraph');
assert.equal(byKey('maneuver:Gutstrike').save, 'Fortitude negates · DC {= 11 + wis.mod}');
assert.equal(byKey("veil:Marilith's Aspect").note, 'Grow two arms.', 'a shaped veil reads from the veil catalogue');
assert.equal(byKey("veil:Marilith's Aspect").detail, 'Shoulders · Fleshwarp');
assert.ok(!sessionShortcuts(m).some(s => s.key === "ability:Marilith's Aspect"), 'and is not also listed as a bare ability');
const pickers = Object.fromEntries([...renderSessionBoard(m).matchAll(/<select data-session-shortcut="(\w+)"[^>]*>(.*?)<\/select>/gs)].map(x => [x[1], x[2]]));
assert.ok(pickers.standard.includes('maneuver:Gutstrike') && !pickers.swift.includes('maneuver:Gutstrike'), 'a standard strike is offered under Standard only');
assert.ok(pickers.swift.includes('maneuver:Savage Stance') && !pickers.standard.includes('maneuver:Savage Stance'), 'a stance under Swift only');
assert.ok(pickers.standard.includes('maneuver:Odd Trick') && pickers.free.includes('maneuver:Odd Trick'), 'an unplaceable action is offered everywhere');
assert.ok(pickers.standard.includes("veil:Marilith") && pickers.swift.includes("veil:Marilith"), 'a veil is offered everywhere');
m.set('session.cards', [{ title: 'Gutstrike', type: 'swift', source: 'maneuver:Gutstrike' }]);
assert.match(renderSessionBoard(m), /normally a standard action/, 'a moved maneuver says what it normally costs');
setManeuverCatalogue({ disciplines: [] }); setVeilCatalogue({ veils: [] });
console.log('Session actions: relationships, formulas, costs, undo, persistence and shortcuts passed');
