import assert from 'node:assert/strict';
import { Character } from '../app/js/model.js';
import { blankDocument } from '../app/js/convert.js';
import { editableSession, moveSessionCard, removeSessionCard, choiceParent } from '../app/js/model/session-layout.js';
import { renderSessionBoard } from '../app/js/ui/panels/session.js';
import { sessionState, useSessionAction } from '../app/js/model/session.js';
const m = new Character(blankDocument({name:'Choices',level:5}));
m.set('session', {cards:[{title:'Fire',type:'standard',damageFormula:'2d6'}, {title:'Cold',type:'standard',damageFormula:'3d6'}, {title:'Step',type:'move'}],folded:{'editor:0':false}});
const s = editableSession(m);
s.cards.push({id:'blasts',kind:'choice',title:'Blasts',type:'standard'});
m.set('session',s);
const id = title => m.data.session.cards.findIndex(c => c.title === title);
moveSessionCard(m,id('Fire'),{type:'standard',groupId:'blasts'});
moveSessionCard(m,id('Cold'),{type:'standard',groupId:'blasts'});
assert.equal(choiceParent(sessionState(m),m.data.session.cards[id('Fire')]).title,'Blasts');
let html = renderSessionBoard(m);
assert.equal((html.match(/class="session-option /g)||[]).length,2,'only one child plus standalone Step');
assert.ok(html.includes('2d6'));
assert.ok(!html.includes('<strong>3d6</strong>'),'other child hidden');
m.set(`session.cards.${id('Blasts')}.selectedId`,m.data.session.cards[id('Cold')].id);
assert.ok(renderSessionBoard(m).includes('<strong>3d6</strong>'));
assert.equal(useSessionAction(m,m.data.session.cards[id('Cold')]),'');
assert.equal(m.data.session.spent.standard,1);
assert.match(useSessionAction(m,m.data.session.cards[id('Blasts')]),/Select an option/);
moveSessionCard(m,id('Blasts'),{type:'full'});
assert.equal(m.data.session.cards[id('Fire')].type,'full');
assert.equal(m.data.session.cards[id('Cold')].type,'full');
assert.equal(moveSessionCard(m,id('Blasts'),{type:'full',groupId:'blasts'}),false,'no nested/self groups');
moveSessionCard(m,id('Cold'),{type:'full',groupId:'blasts',target:id('Fire')});
assert.ok(id('Cold') < id('Fire'));
assert.equal(m.data.session.folded[`editor:${id('Fire')}`],false,'folds follow moved cards');
const reopened = new Character(JSON.parse(JSON.stringify(m.toJSON())));
assert.deepEqual(sessionState(reopened),sessionState(m));
removeSessionCard(m,id('Blasts'));
assert.ok(m.data.session.cards.every(c => !c.groupId));
assert.equal(m.data.session.cards.length,3,'ungroup preserves children');
m.undo();
assert.ok(m.data.session.cards.some(c => c.kind === 'choice'));
moveSessionCard(m,id('Fire'),{type:'move'});
assert.equal(m.data.session.cards[id('Fire')].groupId,'','moving out ungroups card');
console.log('Session layout: grouping, selection, moves, folds, persistence and undo passed');
